---
title: "April 23 Overview"
output: 
  html_document:
    css: overview.css
---

Midterm 03 has two parts. Both parts are due at **5pm on Tuesday, April 28**. **BOTH PARTS REQUIRE SUBMISSIONS ON CANVAS**

## Part 01

1. The first part of this exam is intended to take no more than 75 minutes (I expect it may take even less time), you will have 2 hours from when you begin the exam to turn it in. The exam **must** be turned in by Tuesday, April 28, at 5pm Eastern.
2. **You can find the exam on Canvas under "Quizzes" Midterm 03: Part 1**
3. You should complete this exam in Google Chrome.

This exam is open book. Open book exams are defined as follows: 

* Any course materials, including books, videos, and notes, may be used for the exam. 
* Students may not communicate in any way with other students or individuals during the exam period. This includes chatting, videos, photos, phone calls, and all other forms of communication. 
* Students may not share answers, hints, questions, or any information relating to the exam online in any format. This includes, but is not limited to, any websites or online communication platforms.  
* All submitted work must be the student’s work, and must be submitted in the student’s own words. 
* All exams must be submitted on Canvas by the 5pm on April 28. Late exams will not be accepted. 
* Any violation of this Honor Code will be reported to the Wake Forest Honor Council, and will result in, at a minimum, a zero on the exam. 

## Part 02

1. The second part of this exam is an _analysis_. I have provided you with a data set in a GitHub repo - search for `midterm-03` on our class GitHub site (https://github.com/sta-363-s20)
2. The goal is to predict `y` using any of the 30 variables provided. You may use any techniques we have learned so far.
3. I have held out some _test_ data that I will try on your model.
4. When you have finished the analysis portion, submit your _final model_ on Canvas. **You can find this portion of the exam on Canvas under "Quizzes": Midterm 03: Part 2.**
5. You will need to specify:

* The final model specification
* The final model fit
* OPTIONALLY: a recipe (should you choose to use one)

The final model specification should be submitted in the following form:

```
final_spec <- -----() %>%
   set_engine(----)
```

The final model fit should be submitted in the following form:

```
final_fit <- fit(
  final_spec,
   ------,
   data = dat) 
```